"""empty message

Revision ID: 1ed9dae26baa
Revises: 
Create Date: 2025-04-15 23:03:07.451275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed9dae26baa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('flag_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.create_table('timezones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timezones_id'), 'timezones', ['id'], unique=False)
    op.create_index(op.f('ix_timezones_name'), 'timezones', ['name'], unique=True)
    op.create_table('leagues',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('has_standings', sa.Boolean(), nullable=True),
    sa.Column('has_players', sa.Boolean(), nullable=True),
    sa.Column('has_top_scorers', sa.Boolean(), nullable=True),
    sa.Column('has_top_assists', sa.Boolean(), nullable=True),
    sa.Column('has_top_cards', sa.Boolean(), nullable=True),
    sa.Column('has_injuries', sa.Boolean(), nullable=True),
    sa.Column('has_predictions', sa.Boolean(), nullable=True),
    sa.Column('has_odds', sa.Boolean(), nullable=True),
    sa.Column('has_events', sa.Boolean(), nullable=True),
    sa.Column('has_lineups', sa.Boolean(), nullable=True),
    sa.Column('has_fixture_stats', sa.Boolean(), nullable=True),
    sa.Column('has_player_stats', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('league_id'),
    sa.UniqueConstraint('external_id', 'season', name='uq_league_external_id_season')
    )
    op.create_index(op.f('ix_leagues_is_current'), 'leagues', ['is_current'], unique=False)
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_is_current'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_timezones_name'), table_name='timezones')
    op.drop_index(op.f('ix_timezones_id'), table_name='timezones')
    op.drop_table('timezones')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
