"""fix_leagues_table_for_fk_constraint

Revision ID: 23070c56b986
Revises: cf8faf7e3bcf
Create Date: 2025-05-19 09:04:13.821928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23070c56b986'
down_revision: Union[str, None] = 'cf8faf7e3bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('season', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'season')
    # ### end Alembic commands ###
