"""add unique to coach career table

Revision ID: 30c67aebe86c
Revises: 518770b79653
Create Date: 2025-05-29 17:35:55.161982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c67aebe86c'
down_revision: Union[str, None] = '518770b79653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_coach_career_query', 'coaches_careers', ['coach_id', 'team_id'], unique=False)
    op.create_unique_constraint('uq_coach_team_start_career', 'coaches_careers', ['coach_id', 'team_id', 'start_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_coach_team_start_career', 'coaches_careers', type_='unique')
    op.drop_index('ix_coach_career_query', table_name='coaches_careers')
    # ### end Alembic commands ###
