"""Create counrty table

Revision ID: 319d324febfd
Revises: bc77314b50a4
Create Date: 2025-04-14 22:03:17.164887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319d324febfd'
down_revision: Union[str, None] = 'bc77314b50a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_countries_code', table_name='countries')
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.drop_index('ix_countries_name', table_name='countries')
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.create_index('ix_countries_name', 'countries', ['name'], unique=True)
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.create_index('ix_countries_code', 'countries', ['code'], unique=False)
    # ### end Alembic commands ###
