"""create player fixture stats table

Revision ID: 3797375acca2
Revises: a5b1921fac0e
Create Date: 2025-05-23 15:34:55.510540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3797375acca2'
down_revision: Union[str, None] = 'a5b1921fac0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_fixture_stats',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('player_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=True),
    sa.Column('substitute', sa.Boolean(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on', sa.Integer(), nullable=True),
    sa.Column('goals_total', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('goals_assists', sa.Integer(), nullable=True),
    sa.Column('goals_saves', sa.Integer(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_key', sa.Integer(), nullable=True),
    sa.Column('passes_accuracy_percentage', sa.Integer(), nullable=True),
    sa.Column('tackles_total', sa.Integer(), nullable=True),
    sa.Column('tackles_blocks', sa.Integer(), nullable=True),
    sa.Column('tackles_interceptions', sa.Integer(), nullable=True),
    sa.Column('duels_total', sa.Integer(), nullable=True),
    sa.Column('duels_won', sa.Integer(), nullable=True),
    sa.Column('dribbles_attempts', sa.Integer(), nullable=True),
    sa.Column('dribbles_success', sa.Integer(), nullable=True),
    sa.Column('dribbles_past', sa.Integer(), nullable=True),
    sa.Column('fouls_drawn', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('cards_yellow', sa.Integer(), nullable=True),
    sa.Column('cards_red', sa.Integer(), nullable=True),
    sa.Column('penalty_won', sa.Integer(), nullable=True),
    sa.Column('penalty_committed', sa.Integer(), nullable=True),
    sa.Column('penalty_scored', sa.Integer(), nullable=True),
    sa.Column('penalty_missed', sa.Integer(), nullable=True),
    sa.Column('penalty_saved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('player_id', 'match_id', 'team_id', name='uq_player_fixture_team_stats')
    )
    op.create_index(op.f('ix_player_fixture_stats_match_id'), 'player_fixture_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_fixture_stats_player_id'), 'player_fixture_stats', ['player_id'], unique=False)
    op.create_index('ix_player_fixture_stats_query', 'player_fixture_stats', ['player_id', 'match_id'], unique=False)
    op.create_index(op.f('ix_player_fixture_stats_stat_id'), 'player_fixture_stats', ['stat_id'], unique=False)
    op.create_index(op.f('ix_player_fixture_stats_team_id'), 'player_fixture_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_fixture_stats_team_id'), table_name='player_fixture_stats')
    op.drop_index(op.f('ix_player_fixture_stats_stat_id'), table_name='player_fixture_stats')
    op.drop_index('ix_player_fixture_stats_query', table_name='player_fixture_stats')
    op.drop_index(op.f('ix_player_fixture_stats_player_id'), table_name='player_fixture_stats')
    op.drop_index(op.f('ix_player_fixture_stats_match_id'), table_name='player_fixture_stats')
    op.drop_table('player_fixture_stats')
    # ### end Alembic commands ###
