"""add jsdon fields to match table

Revision ID: 3e868417a35f
Revises: bd7ae5ecffd8
Create Date: 2025-05-25 14:26:14.133328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e868417a35f'
down_revision: Union[str, None] = 'bd7ae5ecffd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_lineups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('match_lineups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('matches', sa.Column('team_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'team_stats')
    op.drop_column('match_lineups', 'updated_at')
    op.drop_column('match_lineups', 'created_at')
    # ### end Alembic commands ###
