"""create injury

Revision ID: 74486b718539
Revises: 30c67aebe86c
Create Date: 2025-06-01 11:58:41.798953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74486b718539'
down_revision: Union[str, None] = '30c67aebe86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_country', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('career', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_id'), 'coaches', ['id'], unique=False)
    op.create_index(op.f('ix_coaches_lastname'), 'coaches', ['lastname'], unique=False)
    op.create_index(op.f('ix_coaches_name'), 'coaches', ['name'], unique=False)
    op.create_index(op.f('ix_coaches_team_id'), 'coaches', ['team_id'], unique=False)
    op.create_table('coaches_careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'team_id', 'start_date', name='uq_coach_team_start_career')
    )
    op.create_index('ix_coach_career_query', 'coaches_careers', ['coach_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_coaches_careers_coach_id'), 'coaches_careers', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coaches_careers_id'), 'coaches_careers', ['id'], unique=False)
    op.create_index(op.f('ix_coaches_careers_team_id'), 'coaches_careers', ['team_id'], unique=False)
    op.create_index(op.f('ix_coaches_careers_team_name'), 'coaches_careers', ['team_name'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', name='uq_player_match')
    )
    op.create_index(op.f('ix_injuries_id'), 'injuries', ['id'], unique=False)
    op.create_index(op.f('ix_injuries_match_id'), 'injuries', ['match_id'], unique=False)
    op.create_index(op.f('ix_injuries_player_id'), 'injuries', ['player_id'], unique=False)
    op.create_index(op.f('ix_injuries_team_id'), 'injuries', ['team_id'], unique=False)
    op.create_index('ix_injury_query', 'injuries', ['player_id', 'match_id'], unique=False)
    op.add_column('match_lineups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('match_lineups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_match_lineup_match_team', 'match_lineups', ['match_id', 'team_id'])
    op.add_column('matches', sa.Column('events_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('lineups_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('team_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('player_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'player_stats_json')
    op.drop_column('matches', 'team_stats_json')
    op.drop_column('matches', 'lineups_json')
    op.drop_column('matches', 'events_json')
    op.drop_constraint('uq_match_lineup_match_team', 'match_lineups', type_='unique')
    op.drop_column('match_lineups', 'updated_at')
    op.drop_column('match_lineups', 'created_at')
    op.drop_index('ix_injury_query', table_name='injuries')
    op.drop_index(op.f('ix_injuries_team_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_player_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_match_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_id'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index(op.f('ix_coaches_careers_team_name'), table_name='coaches_careers')
    op.drop_index(op.f('ix_coaches_careers_team_id'), table_name='coaches_careers')
    op.drop_index(op.f('ix_coaches_careers_id'), table_name='coaches_careers')
    op.drop_index(op.f('ix_coaches_careers_coach_id'), table_name='coaches_careers')
    op.drop_index('ix_coach_career_query', table_name='coaches_careers')
    op.drop_table('coaches_careers')
    op.drop_index(op.f('ix_coaches_team_id'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_name'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_lastname'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_id'), table_name='coaches')
    op.drop_table('coaches')
    # ### end Alembic commands ###
