"""Update League table

Revision ID: 765d250f9eb6
Revises: e763f12c2e89
Create Date: 2025-04-15 16:59:45.104731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765d250f9eb6'
down_revision: Union[str, None] = 'e763f12c2e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_league_external_id_season', 'leagues', ['external_id', 'season'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_league_external_id_season', 'leagues', type_='unique')
    # ### end Alembic commands ###
