"""Update venue table change name to nullable

Revision ID: 770ef27bb8df
Revises: 8e9b56b83e3a
Create Date: 2025-04-16 19:11:33.974854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770ef27bb8df'
down_revision: Union[str, None] = '8e9b56b83e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               existing_comment='Venue name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               existing_comment='Venue name')
    # ### end Alembic commands ###
