"""delete country id

Revision ID: 79ba03f3b32b
Revises: ff9baf65d629
Create Date: 2025-04-27 05:28:54.933375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ba03f3b32b'
down_revision: Union[str, None] = 'ff9baf65d629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('country', sa.String(length=255), nullable=True))
    op.drop_index('ix_teams_country_id', table_name='teams')
    op.drop_constraint('teams_country_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'country_id')
    op.drop_constraint('venues_country_id_fkey', 'venues', type_='foreignkey')
    op.drop_column('venues', 'country_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('venues_country_id_fkey', 'venues', 'countries', ['country_id'], ['country_id'])
    op.add_column('teams', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('teams_country_id_fkey', 'teams', 'countries', ['country_id'], ['country_id'])
    op.create_index('ix_teams_country_id', 'teams', ['country_id'], unique=False)
    op.drop_column('teams', 'country')
    # ### end Alembic commands ###
