"""Create counrty table

Revision ID: 7c70abb27f06
Revises: e5a669baf970
Create Date: 2025-04-14 20:07:05.317593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c70abb27f06'
down_revision: Union[str, None] = 'e5a669baf970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('flag', sa.String(length=255), nullable=True))
    op.drop_column('countries', 'logo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('countries', 'flag')
    # ### end Alembic commands ###
