"""Create timezones table

Revision ID: 8a648874dd92
Revises: 28c062f85692
Create Date: 2025-04-14 14:54:03.766265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a648874dd92'
down_revision: Union[str, None] = '28c062f85692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timezones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_timezone_name')
    )
    op.create_index(op.f('ix_timezones_id'), 'timezones', ['id'], unique=False)
    op.create_index(op.f('ix_timezones_name'), 'timezones', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timezones_name'), table_name='timezones')
    op.drop_index(op.f('ix_timezones_id'), table_name='timezones')
    op.drop_table('timezones')
    # ### end Alembic commands ###
