"""Create teams venues again tables

Revision ID: 8e9b56b83e3a
Revises: 819931ec55f9
Create Date: 2025-04-16 15:03:21.303990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9b56b83e3a'
down_revision: Union[str, None] = '819931ec55f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment='Venue ID from API-Football'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Venue name'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='Venue address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City where the venue is located'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Venue capacity'),
    sa.Column('surface', sa.String(length=50), nullable=True, comment='Playing surface (e.g., grass, artificial)'),
    sa.Column('image_url', sa.String(length=255), nullable=True, comment='URL of the venue image'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index(op.f('ix_venues_external_id'), 'venues', ['external_id'], unique=True)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_index(op.f('ix_venues_venue_id'), 'venues', ['venue_id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment='Team ID from API-Football'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Team name'),
    sa.Column('code', sa.String(length=10), nullable=True, comment='Team code (e.g., 3-letter code)'),
    sa.Column('founded', sa.Integer(), nullable=True, comment='Year the team was founded'),
    sa.Column('is_national', sa.Boolean(), nullable=False, comment="True if it's a national team"),
    sa.Column('logo_url', sa.String(length=255), nullable=True, comment='URL of the team logo'),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_country_id'), 'teams', ['country_id'], unique=False)
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.create_index(op.f('ix_teams_is_national'), 'teams', ['is_national'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_teams_venue_id'), 'teams', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_venue_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_is_national'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_country_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_venues_venue_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_external_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
