"""create event table

Revision ID: a09dc434d15b
Revises: 55db3b05dfba
Create Date: 2025-05-21 06:14:44.942833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09dc434d15b'
down_revision: Union[str, None] = '55db3b05dfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_events',
    sa.Column('match_event_id', sa.Integer(), nullable=False),
    sa.Column('time_elapsed', sa.Integer(), nullable=False),
    sa.Column('time_extra', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_detail', sa.String(length=255), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('assist_player_id', sa.Integer(), nullable=True),
    sa.Column('team_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('player_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('assist_player_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assist_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('match_event_id')
    )
    op.create_index(op.f('ix_match_events_assist_player_id'), 'match_events', ['assist_player_id'], unique=False)
    op.create_index(op.f('ix_match_events_match_event_id'), 'match_events', ['match_event_id'], unique=False)
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_events_player_id'), 'match_events', ['player_id'], unique=False)
    op.create_index(op.f('ix_match_events_team_id'), 'match_events', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_events_team_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_player_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_match_event_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_assist_player_id'), table_name='match_events')
    op.drop_table('match_events')
    # ### end Alembic commands ###
