"""create team stats table

Revision ID: a5b1921fac0e
Revises: a09dc434d15b
Create Date: 2025-05-21 14:04:48.589381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b1921fac0e'
down_revision: Union[str, None] = 'a09dc434d15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_team_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('shots_on_goal', sa.Integer(), nullable=True),
    sa.Column('shots_off_goal', sa.Integer(), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=True),
    sa.Column('blocked_shots', sa.Integer(), nullable=True),
    sa.Column('shots_insidebox', sa.Integer(), nullable=True),
    sa.Column('shots_outsidebox', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('corner_kicks', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('ball_possession', sa.String(length=10), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('goalkeeper_saves', sa.Integer(), nullable=True),
    sa.Column('total_passes', sa.Integer(), nullable=True),
    sa.Column('passes_accurate', sa.Integer(), nullable=True),
    sa.Column('passes_percentage', sa.String(length=10), nullable=True),
    sa.Column('raw_statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_team_statistic')
    )
    op.create_index(op.f('ix_match_team_statistics_id'), 'match_team_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_match_team_statistics_match_id'), 'match_team_statistics', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_team_statistics_team_id'), 'match_team_statistics', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_team_statistics_team_id'), table_name='match_team_statistics')
    op.drop_index(op.f('ix_match_team_statistics_match_id'), table_name='match_team_statistics')
    op.drop_index(op.f('ix_match_team_statistics_id'), table_name='match_team_statistics')
    op.drop_table('match_team_statistics')
    # ### end Alembic commands ###
