"""add unique condition to lineups table

Revision ID: bd40c932d853
Revises: 485d2b8dee57
Create Date: 2025-05-26 18:00:30.678870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd40c932d853'
down_revision: Union[str, None] = '485d2b8dee57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_lineup_match_team', 'match_lineups', ['match_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_lineup_match_team', 'match_lineups', type_='unique')
    # ### end Alembic commands ###
