"""create match table

Revision ID: cf8faf7e3bcf
Revises: 2993105427f5
Create Date: 2025-05-19 08:31:57.268379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8faf7e3bcf'
down_revision: Union[str, None] = '2993105427f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('referee', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('periods_first', sa.Integer(), nullable=True),
    sa.Column('periods_second', sa.Integer(), nullable=True),
    sa.Column('status_long', sa.String(length=50), nullable=False),
    sa.Column('status_short', sa.String(length=10), nullable=False),
    sa.Column('status_elapsed', sa.Integer(), nullable=True),
    sa.Column('status_extra', sa.Integer(), nullable=True),
    sa.Column('goals_home', sa.Integer(), nullable=True),
    sa.Column('goals_away', sa.Integer(), nullable=True),
    sa.Column('score_halftime_home', sa.Integer(), nullable=True),
    sa.Column('score_halftime_away', sa.Integer(), nullable=True),
    sa.Column('score_fulltime_home', sa.Integer(), nullable=True),
    sa.Column('score_fulltime_away', sa.Integer(), nullable=True),
    sa.Column('score_extratime_home', sa.Integer(), nullable=True),
    sa.Column('score_extratime_away', sa.Integer(), nullable=True),
    sa.Column('score_penalty_home', sa.Integer(), nullable=True),
    sa.Column('score_penalty_away', sa.Integer(), nullable=True),
    sa.Column('winner_home', sa.Boolean(), nullable=True),
    sa.Column('winner_away', sa.Boolean(), nullable=True),
    sa.Column('round', sa.String(length=100), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
#    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
#    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_matches_venue_id'), 'matches', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_venue_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
