"""Correct unique constraint on leagues table for external_id and season

Revision ID: e682b9f60fbc
Revises: 765d250f9eb6
Create Date: 2025-04-15 20:33:42.430773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e682b9f60fbc'
down_revision: Union[str, None] = '765d250f9eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('leagues_external_id_key', 'leagues', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('leagues_external_id_key', 'leagues', ['external_id'])
    op.alter_column('leagues', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
