"""Change country table

Revision ID: e763f12c2e89
Revises: 322e54b9668b
Create Date: 2025-04-15 16:20:43.950940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e763f12c2e89'
down_revision: Union[str, None] = '322e54b9668b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
