"""edit match table

Revision ID: edad52275ae3
Revises: 3e868417a35f
Create Date: 2025-05-26 07:30:05.941539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edad52275ae3'
down_revision: Union[str, None] = '3e868417a35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('events_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('lineups_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('team_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('player_stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('matches', 'team_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('team_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('matches', 'player_stats_json')
    op.drop_column('matches', 'team_stats_json')
    op.drop_column('matches', 'lineups_json')
    op.drop_column('matches', 'events_json')
    # ### end Alembic commands ###
